import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {performance} from 'node:perf_hooks';import {server} from '../server.mjs';
const results={date:new Date().toISOString(),api:[],browser:[],performance:[],limitations:['Mock owner header is not authentication/RLS','Headless software rendering is not a consumer device/GPU benchmark','No commercial tiles, geocoder, production AI or Community export','No real financial observations or investment recommendations']};
await new Promise(r=>server.listen(4173,'127.0.0.1',r));const base='http://127.0.0.1:4173';let browser;
async function check(name,fn,group='api'){try{await fn();results[group].push({name,passed:true});}catch(e){results[group].push({name,passed:false,error:String(e)});console.log('FAIL',name,String(e));}}
async function api(url,owner){const r=await fetch(base+url,{headers:owner?{'X-Mock-Owner':owner}:{}});return{status:r.status,data:await r.json()};}
try{
 await check('Research pagination and link-only text exclusion',async()=>{const a=await api('/api/research?geo=Vancouver','A');assert.equal(a.data.items[0].id,'approved-summary');assert.equal(a.data.nextCursor,'1');const b=await api('/api/research?geo=Vancouver&cursor=1','A');assert.equal(b.data.items[0].rights,'link-only');assert.equal(b.data.items[0].summary,undefined);assert.equal(b.data.nextCursor,null);});
 await check('Direct hidden/withdrawn/withheld detail denied',async()=>{for(const id of ['draft-secret','withdrawn-secret','withheld-secret','missing']){assert.equal((await api('/api/research/'+id,'A')).status,404);}});
 await check('Public audience cannot read member item',async()=>{assert.equal((await api('/api/research/approved-summary')).status,404);assert.equal((await api('/api/research/approved-link')).status,200);});
 await check('Link-only direct detail omits text',async()=>{const d=await api('/api/research/approved-link','A');assert(!JSON.stringify(d).includes('MUST_NOT_EXPOSE'));});
 await check('Empty/error/invalid pagination distinguishable',async()=>{assert.deepEqual((await api('/api/research?mode=empty','A')).data.items,[]);assert.equal((await api('/api/research?mode=error','A')).status,503);assert.equal((await api('/api/research?cursor=-1','A')).status,400);});
 await check('Portfolio mock isolation and unauthenticated denial',async()=>{for(const o of ['A','B'])assert((await api('/api/holdings',o)).data.items.every(h=>h.owner===o));assert.equal((await api('/api/holdings')).status,401);});
 await check('Internal fixture server source not publicly served',async()=>{assert.equal((await fetch(base+'/server.mjs')).status,404);});
 const {chromium}=await import('playwright');const {default:binary}=await import('@sparticuz/chromium');const {default:AxeBuilder}=await import('@axe-core/playwright');
 for(const renderer of ['maplibre','leaflet']){
 browser=await chromium.launch({executablePath:process.env.REVIEW_CHROMIUM_PATH||undefined,args:[...binary.args,'--enable-unsafe-swiftshader'],headless:true});results.environment={browser:browser.version(),platform:process.platform,node:process.version,rendererPackages:{maplibre:'5.20.0',leaflet:'1.9.4'}};

  const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce',hasTouch:true});const page=await context.newPage();const errors=[],remote=[];page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))remote.push(r.url());});
  async function ready(){await page.waitForFunction(()=>window.review?.booted&&document.querySelector('#map-status').textContent.startsWith('Map ready'),{},{timeout:30000});}
  await check(renderer+' boot real renderer',async()=>{await page.goto(base+'/?renderer='+renderer);await ready();assert.equal(await page.locator(renderer==='maplibre'?'.maplibregl-canvas':'.leaflet-container').count(),1);},'browser');
  if(!await page.evaluate(()=>window.review?.booted)){await context.close();continue;}
  await check(renderer+' real map click ambiguity/no-match policy',async()=>{await page.selectOption('#family','ambiguity');await ready();const pixel=await page.evaluate(()=>window.review.pixel([-123.115,49.26]));await page.locator('#map').click({position:{x:pixel.x,y:pixel.y}});assert.equal(await page.locator('#ambiguity button').count(),2);await page.locator('#ambiguity button').first().click();assert.equal(await page.locator('#ambiguity button').count(),0);const before=await page.evaluate(()=>window.review.state.selected);await page.evaluate(()=>window.review.choosePoint([0,0]));assert.equal(await page.evaluate(()=>window.review.state.selected),before);assert.match(await page.locator('#map-status').innerText(),/No boundary match/);},'browser');
  await page.selectOption('#family','city');await ready();await page.selectOption('#area','statcan:city:2021:5915022');
  await check(renderer+' research pagination, dates and detail states',async()=>{await page.waitForFunction(()=>!document.querySelector('#more').hidden);assert.match(await page.locator('#research').innerText(),/publication unknown/);await page.click('#more');await page.waitForFunction(()=>document.querySelector('#research').textContent.includes('link-only'));await page.locator('#research button').last().click();await page.waitForFunction(()=>document.querySelector('#detail').textContent.includes('Link-only'));assert(!await page.locator('body').innerText().then(t=>t.includes('MUST_NOT_EXPOSE')));await page.evaluate(()=>window.review.detail('withdrawn-secret'));await page.waitForFunction(()=>document.querySelector('#detail').textContent.includes('unavailable'));},'browser');
  await check(renderer+' API empty and error views recover',async()=>{await page.selectOption('#mode','empty');await page.waitForFunction(()=>document.querySelector('#research').textContent.includes('No approved'));await page.selectOption('#mode','error');await page.waitForFunction(()=>document.querySelector('#research').textContent.includes('API error'));await page.selectOption('#mode','normal');await page.waitForFunction(()=>document.querySelector('#research button'));},'browser');
  await check(renderer+' stale evidence cannot overwrite new geography',async()=>{await page.selectOption('#mode','delayed');await page.selectOption('#area','statcan:city:2021:3520005');await page.selectOption('#area','statcan:city:2021:5915022');await page.waitForFunction(()=>document.querySelector('#research button'));assert.match(await page.locator('#selection').innerText(),/Vancouver/);assert.match(await page.locator('#research').innerText(),/Vancouver/);await page.selectOption('#mode','normal');},'browser');
  await check(renderer+' portfolio opt-in and account switch clearing',async()=>{assert(!(await page.evaluate(()=>window.review.telemetry.network)).includes('/api/holdings'));await page.check('#portfolio');await ready();assert.match(await page.locator('#holdings').innerText(),/Unmapped/);await page.selectOption('#owner','B');await ready();assert.match(await page.locator('#holdings').innerText(),/Account B/);assert(!/Sample development|Sample investment|Unmapped holding/.test(await page.locator('#holdings').innerText()));await page.uncheck('#portfolio');await ready();await page.selectOption('#owner','A');await ready();},'browser');
  await check(renderer+' ribbon retention and hidden renderer disposal',async()=>{await page.click('#compare');const before=await page.evaluate(()=>structuredClone(window.review.state));await page.locator('[data-module="Dev Studio"]').click();assert.equal(await page.evaluate(()=>window.review.telemetry.alive),0);assert.equal(await page.locator('.maplibregl-canvas,.leaflet-pane').count(),0);await page.click('#return');await ready();const after=await page.evaluate(()=>window.review.state);assert.equal(after.selected,before.selected);assert.deepEqual(after.comparison,before.comparison);assert.deepEqual(after.camera,before.camera);},'browser');
  await check(renderer+' keyboard alternate geographic selection',async()=>{await page.locator('#area').focus();await page.keyboard.press('ArrowUp');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'area');},'browser');
  await page.selectOption('#area','statcan:city:2021:5915022');await page.waitForFunction(()=>document.querySelector('#research button'));
  await check(renderer+' zero and missing quantitative states',async()=>{assert.match(await page.locator('#metrics').innerText(),/index: 0/);await page.selectOption('#family','state');await ready();assert.match(await page.locator('#metrics').innerText(),/unavailable/);await page.selectOption('#family','city');await ready();await page.selectOption('#area','statcan:city:2021:5915022');},'browser');
  for(const width of [1440,390,320]){await page.setViewportSize({width,height:width===1440?1000:844});for(const dark of [false,true]){
   if((await page.locator('body').getAttribute('class')||'').includes('dark')!==dark){await page.click('#theme');await ready();}
   await page.click('#fit');
   await check(`${renderer} ${width} ${dark?'dark':'light'} layout/a11y`,async()=>{assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const a=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();const severe=a.violations.filter(v=>['serious','critical'].includes(v.impact));assert.deepEqual(severe.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);},'browser');
   await page.screenshot({path:`evidence/${renderer}-${width}-${dark?'dark':'light'}.png`,fullPage:true});
  }}
  await check(renderer+' touch boundary selection',async()=>{await page.selectOption('#family','ambiguity');await ready();const pixel=await page.evaluate(()=>window.review.pixel([-123.115,49.26]));const box=await page.locator('#map').boundingBox();await page.touchscreen.tap(box.x+pixel.x,box.y+pixel.y);assert.equal(await page.locator('#ambiguity button').count(),2);await page.selectOption('#family','city');await ready();await page.selectOption('#area','statcan:city:2021:5915022');},'browser');
  await page.setViewportSize({width:1440,height:1000});
  for(const v of ['100','1000','10000']){await page.selectOption('#volume',v);await ready();const d=await page.evaluate(()=>window.review.telemetry.renders.at(-1));assert.equal(d.volume,Number(v));results.performance.push({...d,kind:'point-stress',viewport:'1440x1000'});}
  await page.selectOption('#volume','0');await ready();for(const v of ['1000','10000','50000']){await page.selectOption('#complexity',v);await ready();const d=await page.evaluate(()=>window.review.telemetry.renders.at(-1));assert.equal(d.complexity,Number(v));results.performance.push({...d,kind:'vertex-stress',viewport:'1440x1000'});}await page.selectOption('#complexity','0');await ready();
  await check(renderer+' no unexpected renderer errors or external requests',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);assert.deepEqual(await page.evaluate(()=>window.review.telemetry.errors),[]);},'browser');
  // Five cold HTTP cache loads (same isolated context; browser process warm) and five warm same-context reloads.
  for(let i=0;i<5;i++){await page.goto('about:blank');const cdp=await context.newCDPSession(page);await cdp.send('Network.clearBrowserCache');await cdp.detach();let t=performance.now();await page.goto(base+'/?renderer='+renderer);await ready();results.performance.push({renderer,kind:'cold-http-cache-load',run:i+1,ms:performance.now()-t});}
  for(let i=0;i<5;i++){let t=performance.now();await page.reload();await ready();results.performance.push({renderer,kind:'warm-reload',run:i+1,ms:performance.now()-t});}
  results.performance.push({renderer,kind:'panel-dom-after-response',samples:await page.evaluate(()=>window.review.telemetry.panels)});await check(renderer+' default preview selects Leaflet',async()=>{await page.goto(base+'/');await ready();assert.equal(await page.locator('#renderer').inputValue(),'leaflet');},'browser');await context.close();await browser.close();browser=null;
 }
}catch(e){results.fatal=String(e);console.log('Fatal',String(e));}finally{await browser?.close();await new Promise(r=>server.close(r));await fs.writeFile('evidence/test-results.json',JSON.stringify(results,null,2));}
console.log(JSON.stringify({api:results.api,browser:results.browser,environment:results.environment,fatal:results.fatal,performance:results.performance},null,2));if(results.fatal||[...results.api,...results.browser].some(x=>!x.passed))process.exitCode=1;
